import type { ProviderKey } from "./providers";

export type ContextualOffer = { provider: ProviderKey; label: string; fit: string; numbers: string; watch: string };
export type ComparisonProfile = { heading: string; intro: string; winner: ProviderKey; winnerReason: string; offers: ContextualOffer[] };

const offer = (provider: ProviderKey, label: string, fit: string, numbers: string, watch: string): ContextualOffer => ({ provider, label, fit, numbers, watch });
const baseOffers = [
  offer("svarta-ladan", "Helhetsval för vardagen", "Dig som vill ha färdiglagat med fler kostval och en tydlig veckorytm.", "Från 78 kr per portion enligt aktuellt underlag.", "Kontrollera leverans till ditt postnummer och rättens innehåll."),
  offer("factor", "För tydliga kostmål", "Dig som väljer efter protein, keto eller kalorier snarare än klassisk husmanskost.", "Cirka 110–140 kr per rätt, plus frakt enligt underlag.", "Räkna in frakt och kontrollera veckans meny."),
  offer("macro-meals", "För näringskoll", "Dig som vill se deklarerade makron och välja måltider med proteinfokus.", "Cirka 115 kr per portion enligt underlag.", "Se minimiantal, leveransdag och aktuell menyrad."),
  offer("fardiga-maten", "För enkel husmanskost", "Dig som främst vill ha klassisk, färdig mat till ett lägre portionsriktmärke.", "Från 65 kr per portion enligt jämförelseunderlag.", "Kontrollera portionsstorlek, område och eventuella tillägg."),
];

const profiles: Record<string, ComparisonProfile> = {
  "basta-fardiga-matlador": { heading: "Fyra färdiglagade tjänster, fyra vardagar", intro: "Vi jämför hur måltiderna är upplagda, vad som går att se om näringen, vad en portion kostar och om leveransen kan fungera hos dig.", winner: "svarta-ladan", winnerReason: "Svarta Lådan är vårt helhetsval eftersom tjänsten kombinerar färdiglagad vardagsmat med flera tydliga kostinriktningar. Leveransområde och exakt meny måste fortfarande kontrolleras före köp.", offers: baseOffers },
  "matlador-med-hemleverans": { heading: "Hemleverans som ska fungera hela vägen hem", intro: "Kyld leverans kan vara avgörande när du köper färdig mat. Börja med postnummer, leveransdag och hur många rätter du faktiskt behöver.", winner: "svarta-ladan", winnerReason: "Svarta Lådan är ett bra första val när du vill ha kylda portioner och fler kostval i samma tjänst.", offers: [baseOffers[0], baseOffers[2], baseOffers[1], baseOffers[3]] },
  "nyttiga-matlador": { heading: "Näring som går att kontrollera", intro: "En nyttig matlåda behöver mer än en välformulerad etikett. Vi tittar efter energi, protein, ingredienser och vad som faktiskt går att välja i den aktuella menyn.", winner: "macro-meals", winnerReason: "Macro Meals blir vårt förstaval här eftersom protein och energi redovisas tydligt per rätt, vilket underlättar en genomtänkt jämförelse.", offers: [baseOffers[2], baseOffers[0], baseOffers[1], baseOffers[3]] },
  "matlador-for-traning": { heading: "Färdig mat för träning och återhämtning", intro: "Träningsmat ska göra det lätt att se protein, portionsstorlek och energi. Det kan inte ersätta individuell kostrådgivning.", winner: "macro-meals", winnerReason: "Macro Meals har tydligast deklarerad protein- och energiinformation i jämförelsen, vilket gör tjänsten enkel att kontrollera mot egna mål.", offers: [baseOffers[2], baseOffers[1], baseOffers[0], baseOffers[3]] },
  "matlador-for-viktnedgang": { heading: "Portionskontroll utan förenklade löften", intro: "Välj inte efter en rubrik om viktnedgång. Jämför istället energi, portionsstorlek, mättnad och om måltiderna fungerar som en del av din vanliga vardag.", winner: "factor", winnerReason: "Factor blir relevant när du vill välja måltider med ett tydligt energitak och se den deklarerade profilen innan du beställer.", offers: [baseOffers[1], baseOffers[0], baseOffers[2], baseOffers[3]] },
  "fardiga-matlador-for-en-person": { heading: "En portions vardag utan storköp", intro: "För en person blir frakt och minsta beställning ofta större delar av kostnaden. Färdiga portioner kan samtidigt minska både planering och svinn.", winner: "svarta-ladan", winnerReason: "Svarta Lådan blir vårt första alternativ när färdiglagat, variation och möjlighet att välja en kostinriktning ska samsas i en enpersonsvecka.", offers: [baseOffers[0], baseOffers[3], baseOffers[2], baseOffers[1]] },
  "billiga-matlador": { heading: "Billigast per portion är bara början", intro: "Det lägsta riktmärket säger inte allt. Räkna med frakt, minsta order, leveransområde och hur många rätter du faktiskt använder.", winner: "fardiga-maten", winnerReason: "Färdiga Maten har det lägsta portionsriktmärket i vår översikt. Det är inte ett löfte om lägsta totalpris för varje beställning.", offers: [baseOffers[3], baseOffers[0], baseOffers[2], baseOffers[1]] },
  "vegetariska-matlador": { heading: "Växtbaserat som behöver läsas rätt", intro: "Kontrollera om en vegetarisk eller vegansk märkning gäller hela menyn, hur allergener redovisas och om leveransen når din adress.", winner: "svarta-ladan", winnerReason: "Svarta Lådan är vår första kontroll för växtbaserade alternativ eftersom tjänsten har en särskild vegolåda enligt den egna produktinformationen.", offers: [baseOffers[0], baseOffers[1], baseOffers[2], baseOffers[3]] },
  "svarta-ladan-recension": { heading: "Svarta Lådan i vardagen", intro: "Vi granskar hur kostval, veckolådor, kyld leverans och aktuell meny fungerar tillsammans.", winner: "svarta-ladan", winnerReason: "Svarta Lådan har ett brett färdiglagat upplägg med olika kostinriktningar. Det passar bäst när du vill slippa köksarbetet men ändå välja riktning för veckan.", offers: [baseOffers[0], baseOffers[2], baseOffers[1]] },
  "factor-recension": { heading: "Factor i vardagen", intro: "Vi granskar hur menyval, kostprofiler, leverans och abonnemang fungerar utan att förvandla recensionen till en topplista.", winner: "factor", winnerReason: "Factor har en tydlig menystruktur för bland annat proteinrikt, keto och energibegränsade måltider. Det kan passa när den deklarerade kostprofilen väger tungt.", offers: [baseOffers[1], baseOffers[2], baseOffers[0]] },
  "macro-meals-recension": { heading: "Macro Meals i vardagen", intro: "Vi granskar näringsvärden, beställningssätt, hemleverans och hur tjänsten fungerar i en normal vecka.", winner: "macro-meals", winnerReason: "Macro Meals gör protein och energi lätta att kontrollera per rätt. Det passar bäst för dig som använder näringsinformationen aktivt.", offers: [baseOffers[2], baseOffers[1], baseOffers[0]] },
  "fardiga-maten-recension": { heading: "Färdiga Maten i vardagen", intro: "Vi granskar prisriktmärke, husmanskost, leverans och de detaljer som avgör om upplägget passar hemma hos dig.", winner: "fardiga-maten", winnerReason: "Färdiga Maten är relevant när klassisk färdig vardagsmat och ett lägre portionsriktmärke är viktigare än nischade kostprofiler.", offers: [baseOffers[3], baseOffers[0], baseOffers[2]] },
};

export function getComparisonProfile(slug: string) {
  return profiles[slug] ?? profiles["basta-fardiga-matlador"];
}
