import type { Metadata } from "next";
import { AffiliateBar } from "./components/AffiliateBar";
import { ProviderComparison } from "./components/ProviderComparison";
import { SiteFooter } from "./components/SiteFooter";
import { SiteHeader } from "./components/SiteHeader";
import { articles } from "./content/articles";
import { SITE_NAME, SITE_URL } from "./content/metadata";
import { providers } from "./content/providers";

const heroImage = "/images/fardiga-matlador/hero-ready-meals.png";
const homeImage = "/images/fardiga-matlador/warm-at-home.png";
const guideSlugs = ["basta-fardiga-matlador", "billiga-matlador", "matlador-med-hemleverans", "nyttiga-matlador", "matlador-for-traning", "matlador-for-viktnedgang", "fardiga-matlador-for-en-person", "vegetariska-matlador"];
const reviewSlugs = ["svarta-ladan-recension", "factor-recension", "macro-meals-recension", "fardiga-maten-recension"];

export const metadata: Metadata = {
  title: "Färdiga matlådor 2026 - jämför hemlevererad färdig mat",
  description: "Jämför färdiga matlådor för hemleverans efter portionspris, kostinriktning, leverans och hur väl de passar din vardag.",
  alternates: { canonical: SITE_URL, languages: { "sv-SE": SITE_URL } },
  openGraph: { title: "Färdiga matlådor 2026", description: "En fristående jämförelse av färdiglagad mat med hemleverans.", url: SITE_URL, siteName: SITE_NAME, locale: "sv_SE", type: "website", images: [{ url: "/images/fardiga-matlador/hero-ready-meals.png", width: 1536, height: 1024, alt: "Färdiglagade matlådor för hemleverans" }] },
  twitter: { card: "summary_large_image", title: "Färdiga matlådor 2026", description: "Jämför färdiglagad mat med hemleverans.", images: ["/images/fardiga-matlador/hero-ready-meals.png"] },
};

export default function Home() {
  const guides = guideSlugs.map((slug) => articles.find((article) => article.slug === slug)).filter(Boolean);
  const reviews = reviewSlugs.map((slug) => articles.find((article) => article.slug === slug)).filter(Boolean);
  const websiteSchema = { "@context": "https://schema.org", "@type": "WebSite", name: SITE_NAME, url: SITE_URL, inLanguage: "sv-SE", dateModified: "2026-08-21", publisher: { "@type": "Organization", name: SITE_NAME, url: SITE_URL } };
  return <><SiteHeader /><main>
    <section className="hero"><div className="hero-copy"><p className="eyebrow">En fristående guide till färdiglagad mat</p><h1>Färdig mat när veckan inte har mer att ge.</h1><p className="lede">Vi jämför färdiga matlådor för hemleverans: portionspris, kostinriktning, leverans och vad som faktiskt behöver fungera mellan jobb, träning och middag.</p><a className="primary-button" href="#jamforelse">Se jämförelsen <span aria-hidden="true">↓</span></a><p className="microcopy">Faktagranskad 21 augusti 2026 · Utbud och priser kan ändras</p></div><figure className="hero-photo"><img src={heroImage} alt="Färdiglagade matlådor med grönsaker och lax på ett ljust köksbord" width="1536" height="1024" /></figure></section>
    <section className="quick-principles" aria-label="Så jämför vi färdiga matlådor"><div><span>01</span><strong>Det som är klart</strong><p>Vi skiljer färdiglagad mat från matkassar med råvaror och recept.</p></div><div><span>02</span><strong>Hela kostnaden</strong><p>Portionspris är en startpunkt. Frakt, minsta order och val av låda påverkar.</p></div><div><span>03</span><strong>Din vanliga vecka</strong><p>Leverans, uppvärmning och kostinriktning väger lika tungt som menyn.</p></div></section>
    <section className="comparison-section" id="jamforelse"><div className="section-heading"><div><p className="eyebrow">Vår helhetsöverblick</p><h2>Färdiglagade matlådor, jämförda för en vanlig vecka</h2></div><p>Vi har valt ut tjänster med färdiglagade portioner som levereras kylda. Vinnaren beror på om du främst vill ha vardagsmat, en tydlig kostprofil eller ett lägre portionsriktmärke.</p></div><div className="winner-preference"><div><p className="eyebrow">Vårt helhetsval</p><h2>Svarta Lådan gör färdiglagat lätt att få in i veckan.</h2><p>Flera kostinriktningar och ett tydligt veckoupplägg gör Svarta Lådan till vårt första val i den breda jämförelsen.</p><p className="preference-caveat">Leveransområde, veckans rätter och innehåll behöver alltid kontrolleras för din adress innan du beställer.</p></div><div className="preference-actions"><a href="/svarta-ladan-recension">Läs recensionen</a><a className="text-link" href="/basta-fardiga-matlador">Så jämför vi ↗</a></div></div><ProviderComparison slug="basta-fardiga-matlador" /><div className="fit-picks"><div><span>Helhetsval</span><strong>Svarta Lådan</strong><p>Färdiglagat med flera tydliga kostinriktningar.</p><a href="/svarta-ladan-recension">Recension ↗</a></div><div><span>För kostmål</span><strong>Factor</strong><p>Keto, proteinrikt och energibegränsat som tydliga menyspår.</p><a href="/factor-recension">Recension ↗</a></div><div><span>För näringskoll</span><strong>Macro Meals</strong><p>Protein och energi redovisas per rätt.</p><a href="/macro-meals-recension">Recension ↗</a></div><div><span>För husmanskost</span><strong>Färdiga Maten</strong><p>Klassisk, färdig vardagsmat med lägre portionsriktmärke.</p><a href="/fardiga-maten-recension">Recension ↗</a></div></div></section>
    <section className="meal-scenes" aria-label="Färdig mat i vardagen"><figure className="meal-scene-main"><img src={homeImage} alt="En person värmer en färdiglagad matlåda hemma i köket" width="1536" height="1024" /><figcaption><span>När tiden styr</span><strong>Färdiglagat passar när middagen ska gå från kyl till tallrik utan ett nytt köksprojekt.</strong><a href="/matlador-med-hemleverans">Jämför hemleverans ↗</a></figcaption></figure><div className="meal-scene-copy"><p className="eyebrow">Välj efter veckan</p><h2>Räkna på måltiden du faktiskt äter.</h2><p>Det lägsta portionspriset är inte alltid det enklaste valet. Läs om frakt, minsta beställning, uppvärmning och meny innan du bestämmer dig.</p><div className="meal-checklist"><p><span>01</span><strong>Kontrollera leveransdag</strong></p><p><span>02</span><strong>Välj rätt antal portioner</strong></p><p><span>03</span><strong>Läs innehåll och kostval</strong></p></div></div></section>
    <section className="cost-example"><div className="cost-copy"><p className="eyebrow">Ett konkret beslut</p><h2>Vad kostar en vecka utan matlagning?</h2><p>Jämför samma antal portioner, lägg till leverans och kontrollera om du kan ändra eller pausa din beställning. Då blir prisbilden mer användbar än en kampanjsiffra.</p><a href="/billiga-matlador">Läs om portionspris <span aria-hidden="true">↗</span></a></div><div className="receipt" aria-label="Frågor före en beställning"><div><span>Portionspris</span><strong>Jämför</strong></div><div><span>Frakt</span><strong>Lägg till</strong></div><div><span>Minsta order</span><strong>Kontrollera</strong></div><div className="receipt-total"><span>Veckokostnad</span><strong>Räkna totalt</strong></div></div></section>
    <section className="all-guides" id="guider"><div className="guide-intro"><div><p className="eyebrow">Guider efter behov</p><h2>Färdig mat för olika vardagar.</h2></div><p>Jämför hemleverans, kostmål, portionspris eller enpersonsveckan för ett val som passar ditt faktiska upplägg.</p></div><div className="editorial-list">{guides.map((guide, index) => guide ? <a href={`/${guide.slug}`} key={guide.slug}><span className="list-number">{String(index + 1).padStart(2, "0")}</span><span><small>{guide.category}</small><strong>{guide.title}</strong></span><span className="list-arrow" aria-hidden="true">↗</span></a> : null)}</div></section>
    <section className="reviews-section"><div className="section-heading"><div><p className="eyebrow">Tjänst för tjänst</p><h2>Recensioner utan genvägar</h2></div><p>Vi beskriver varje tjänsts upplägg, kostprofiler, leverans och vad du behöver kontrollera innan en beställning.</p></div><div className="review-grid">{reviews.map((review) => {
      if (!review) return null;
      const provider = providers.find((candidate) => candidate.reviewSlug === review.slug);
      return <a className={provider?.logo ? "has-review-logo" : undefined} href={`/${review.slug}`} key={review.slug}>{provider?.logo ? <img className="review-logo" src={provider.logo} alt={`${provider.name} logotyp`} /> : <span className="review-letter" aria-hidden="true">{review.title.charAt(0)}</span>}<small>Granskad 21 aug 2026</small><h3>{review.title.split(" recension")[0]}</h3><p>{review.description}</p><strong>Läs recension <span aria-hidden="true">↗</span></strong></a>;
    })}</div></section>
    <section className="trust-section"><div><p className="eyebrow">Vår jämförelseprincip</p><h2>Mer än en prislapp.</h2></div><div><p>Vi jämför färdig mat för den som faktiskt ska äta den: tid, leverans, portionsstorlek, kostinriktning och den totala beställningen.</p><p>Svarta Lådan är vårt helhetsval. Factor och Macro Meals kan vara mer relevanta när näringsprofilen styr. Färdiga Maten har ett lägre portionsriktmärke, men varje beställning behöver räknas separat.</p><p>Uppgifterna är riktmärken från tjänsternas egna sidor och offentligt tillgängligt jämförelseunderlag. Kontrollera alltid veckans meny, innehåll och villkor före köp.</p><a className="text-link" href="/om-oss">Om redaktionen och metoden <span aria-hidden="true">↗</span></a></div></section>
  </main><AffiliateBar /><SiteFooter /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }} /></>;
}
